/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'management',
    path: '/management',
    component: 'layout.base',
    meta: {
      title: 'management',
      i18nKey: 'route.management'
    },
    children: [
      {
        name: 'management_admin',
        path: '/management/admin',
        component: 'view.management_admin',
        meta: {
          title: 'management_admin',
          i18nKey: 'route.management_admin'
        }
      },
      {
        name: 'management_feedback',
        path: '/management/feedback',
        component: 'view.management_feedback',
        meta: {
          title: 'management_feedback',
          i18nKey: 'route.management_feedback'
        }
      },
      {
        name: 'management_membership',
        path: '/management/membership',
        meta: {
          title: 'management_membership',
          i18nKey: 'route.management_membership'
        },
        children: [
          {
            name: 'management_membership_plans',
            path: '/management/membership/plans',
            component: 'view.management_membership_plans',
            meta: {
              title: 'management_membership_plans',
              i18nKey: 'route.management_membership_plans'
            }
          },
          {
            name: 'management_membership_tiers',
            path: '/management/membership/tiers',
            component: 'view.management_membership_tiers',
            meta: {
              title: 'management_membership_tiers',
              i18nKey: 'route.management_membership_tiers'
            }
          }
        ]
      },
      {
        name: 'management_redeem',
        path: '/management/redeem',
        component: 'view.management_redeem',
        meta: {
          title: 'management_redeem',
          i18nKey: 'route.management_redeem'
        }
      }
    ]
  }
];
